# Generated by Django 2.2.4 on 2019-08-30 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fabric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_name', models.CharField(max_length=50)),
                ('img_file', models.ImageField(upload_to='images')),
                ('img_url', models.CharField(max_length=50)),
            ],
        ),
    ]
