# Generated by Django 2.2.4 on 2019-08-30 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabric',
            name='ima_file',
            field=models.FileField(upload_to='images'),
        ),
    ]
