# Generated by Django 2.2.4 on 2019-09-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_auto_20190830_1222'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_name', models.CharField(default='xx', max_length=50)),
                ('img_file', models.FileField(upload_to='images/leather')),
                ('img_url', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='fabric',
            name='img_file',
            field=models.FileField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='img_name',
            field=models.CharField(default='xx', max_length=50),
        ),
    ]
